spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fatihduzenli/config-repo.git
          default-label: master
          username: fatihduzenli
          password: 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
server:
  port: 8888
